# generated-package.nix is auto-generated by regenerate-ghc-ng-packages.sh -- DO NOT EDIT MANUALLY!

{
  mkDerivation,
  alex,
  array,
  base,
  binary,
  bytestring,
  Cabal,
  containers,
  deepseq,
  deriveConstants,
  directory,
  exceptions,
  filepath,
  genprimopcode,
  ghc-boot,
  ghc-boot-th,
  ghc-boot-th-next,
  ghc-heap,
  ghc-internal,
  ghci,
  happy,
  hpc,
  lib,
  os-string,
  process,
  rts,
  semaphore-compat,
  stm,
  time,
  transformers,
  unix,
  flags ? { },
}:
let
  cabalFlags = {
    bootstrap = false;
    build-tool-depends = true;
    dynamic-system-linker = true;
    hadrian-stage0 = false;
    internal-interpreter = false;
  }
  // flags;
in
mkDerivation {
  pname = "ghc";
  version = "9.14.1";
  configureFlags = [
    (if cabalFlags.bootstrap then "-fbootstrap" else "-f-bootstrap")
    (if cabalFlags.build-tool-depends then "-fbuild-tool-depends" else "-f-build-tool-depends")
    (if cabalFlags.dynamic-system-linker then "-fdynamic-system-linker" else "-f-dynamic-system-linker")
    (if cabalFlags.hadrian-stage0 then "-fhadrian-stage0" else "-f-hadrian-stage0")
    (if cabalFlags.internal-interpreter then "-finternal-interpreter" else "-f-internal-interpreter")
  ];
  setupHaskellDepends = [
    base
    Cabal
    containers
    directory
    filepath
    process
  ];
  libraryHaskellDepends = [
    array
    base
    binary
    bytestring
    containers
    deepseq
    directory
    exceptions
    filepath
    ghc-boot
    ghc-heap
    ghci
    hpc
    os-string
    process
    rts
    semaphore-compat
    stm
    time
    transformers
    unix
  ]
  ++ lib.optionals cabalFlags.bootstrap [ ghc-boot-th-next ]
  ++ lib.optionals (!cabalFlags.bootstrap) [
    ghc-boot-th
    ghc-internal
  ];
  libraryToolDepends =
    [ ]
    ++ lib.optionals cabalFlags.build-tool-depends [
      alex
      deriveConstants
      genprimopcode
      happy
    ];
  homepage = "http://www.haskell.org/ghc/";
  description = "The GHC API";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
}
