# generated-package.nix is auto-generated by regenerate-ghc-ng-packages.sh -- DO NOT EDIT MANUALLY!

{
  mkDerivation,
  array,
  base,
  bytestring,
  containers,
  deepseq,
  directory,
  exceptions,
  filepath,
  ghc,
  ghc-boot,
  ghc-paths,
  haddock-library,
  hspec,
  hspec-discover,
  lib,
  mtl,
  parsec,
  QuickCheck,
  transformers,
  unix,
  xhtml,
  flags ? { },
}:
let
  cabalFlags = {
    in-ghc-tree = false;
  }
  // flags;
in
mkDerivation {
  pname = "haddock-api";
  version = "2.33.0";
  configureFlags = [
    (if cabalFlags.in-ghc-tree then "-fin-ghc-tree" else "-f-in-ghc-tree")
  ];
  enableSeparateDataOutput = true;
  libraryHaskellDepends = [
    array
    base
    bytestring
    containers
    deepseq
    directory
    exceptions
    filepath
    ghc
    ghc-boot
    haddock-library
    mtl
    parsec
    transformers
    unix
    xhtml
  ]
  ++ lib.optionals (!cabalFlags.in-ghc-tree) [ ghc-paths ];
  testHaskellDepends = [
    array
    base
    bytestring
    containers
    deepseq
    directory
    exceptions
    filepath
    ghc
    ghc-boot
    ghc-paths
    haddock-library
    hspec
    mtl
    parsec
    QuickCheck
    transformers
    xhtml
  ];
  testToolDepends = [ hspec-discover ];
  homepage = "http://www.haskell.org/haddock/";
  description = "A documentation-generation tool for Haskell libraries";
  license = lib.meta.getLicenseFromSpdxId "BSD-2-Clause";
}
