# generated-package.nix is auto-generated by regenerate-ghc-ng-packages.sh -- DO NOT EDIT MANUALLY!

{
  mkDerivation,
  base,
  filepath,
  haddock-api,
  haddock-test,
  lib,
  flags ? { },
}:
let
  cabalFlags = {
    threaded = true;
  }
  // flags;
in
mkDerivation {
  pname = "haddock";
  version = "2.30.0";
  configureFlags = [
    (if cabalFlags.threaded then "-fthreaded" else "-f-threaded")
  ];
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base
    haddock-api
  ];
  testHaskellDepends = [
    base
    filepath
    haddock-test
  ];
  homepage = "http://www.haskell.org/haddock/";
  description = "A documentation-generation tool for Haskell libraries";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
  mainProgram = "haddock";
}
