# Every Boost library symlinked into one tree.
#
# This is what `boost` is: a dependant that has not been taught about the split
# still finds `${boost}/lib` and `${boost.dev}/include` where they always were.
# Linking against it takes a reference to the join, and so to all of Boost --
# that is the price of the compatibility alias, and the reason to depend on the
# individual libraries instead.
{
  lib,
  stdenv,
  lndir,
  writeText,
  makePkgconfigItem,
  copyPkgconfigItems,
  version,
  # Which libraries to gather: everything the release has, less the ones that
  # were not asked for (Boost.Python, Boost.MPI).
  includedLibraries,
  # Of those, the ones that actually build something. A header-only library is
  # a single output, so its `lib` and its `dev` are the same path -- gathering
  # it into both would put the headers in `out` as well, and the
  # multiple-outputs hook then cannot move `include` over what is already
  # there.
  runtimeLibraries,
  # boostorg/boost_install, for the umbrella CMake package.
  boostInstall,
  # The non-Boost packages the libraries' installed CMake configs call
  # `find_dependency` on -- ICU, the compression libraries and so on.
  externalDependencies,
}:

{
  passthru ? { },
}:

let
  # Reproduces what `b2` writes, from the template in boost-install.jam.
  versionFile = writeText "BoostConfigVersion.cmake" ''
    # Generated by Boost ${version}

    set(PACKAGE_VERSION ${version})

    if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
      set(PACKAGE_VERSION_COMPATIBLE FALSE)
    else()
      set(PACKAGE_VERSION_COMPATIBLE TRUE)
      if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
      endif()
    endif()
  '';
in
stdenv.mkDerivation {
  pname = "boost";
  inherit version;

  dontUnpack = true;

  outputs = [
    "out"
    "dev"
  ];

  nativeBuildInputs = [
    lndir
    copyPkgconfigItems
  ];

  # Not an upstream file: Boost ships no pkg-config metadata, but Meson's Boost
  # detection reads `includedir` and `libdir` out of one, and Nixpkgs has
  # carried this ever since. Dropping it is how `nix` stops finding Boost.
  env = {
    includedir = "${placeholder "dev"}/include";
    libdir = "${placeholder "out"}/lib";
  };

  pkgconfigItems = [
    (makePkgconfigItem {
      name = "boost";
      inherit version;
      variables = {
        includedir = "@includedir@";
        libdir = "@libdir@";
      };
    })
  ];

  installPhase = ''
    runHook preInstall

    mkdir -p "$out" "$dev"
    for library in ${lib.escapeShellArgs (map lib.getLib runtimeLibraries)}; do
      lndir -silent "$library" "$out"
    done
    for library in ${lib.escapeShellArgs (map lib.getDev includedLibraries)}; do
      lndir -silent "$library" "$dev"
    done

    # lndir would leave whichever library it reached first owning
    # `nix-support/propagated-build-inputs`, which is meaningless for a join.
    # The Boost dependencies in those lists are all in here anyway; the
    # external ones are declared as this package's own, below.
    rm -rf "$dev/nix-support"

    # The umbrella CMake package. The superproject installs this and the
    # per-library builds do not, and without it `find_package(Boost COMPONENTS
    # ...)` has nothing to resolve against and falls back to CMake's own
    # FindBoost module, which looks for library files and so cannot find the
    # components upstream builds header-only.
    install -Dm444 -t "$dev/lib/cmake/Boost-${version}" \
      ${boostInstall}/BoostConfig.cmake \
      ${boostInstall}/BoostDetectToolset.cmake

    # The version file is not in the repository: `b2` generates it, from the
    # template in boost-install.jam's make-cmake-config-version. Without it
    # CMake will not accept the config for a versioned `find_package(Boost
    # 1.89)`, which is most of them.
    install -Dm444 ${versionFile} \
      "$dev/lib/cmake/Boost-${version}/BoostConfigVersion.cmake"

    runHook postInstall
  '';

  # A dependant that does `find_package(Boost COMPONENTS iostreams)` has to be
  # able to find BZip2 and the rest itself, because the installed
  # `boost_iostreams-config.cmake` calls `find_dependency` on them.
  propagatedBuildInputs = externalDependencies;

  strictDeps = true;

  inherit passthru;

  meta = {
    description = "Collection of C++ libraries";
    homepage = "https://www.boost.org/";
    license = lib.licenses.boost;
    platforms = lib.platforms.unix ++ lib.platforms.windows;
    # Inherited from Boost.Context, which is in here: it lacks support for the
    # N32 ABI on mips64, and dependants fail very cryptically rather than at
    # build time.
    badPlatforms = [ lib.systems.inspect.patterns.isMips64n32 ];
  };
}
