# generated-package.nix is auto-generated by regenerate-ghc-ng-packages.sh -- DO NOT EDIT MANUALLY!

{
  mkDerivation,
  array,
  base,
  containers,
  deepseq,
  directory,
  filepath,
  happy,
  hpc,
  lib,
  process,
  tasty,
  tasty-golden,
  tasty-hunit,
  text,
  utf8-string,
  flags ? { },
}:
let
  cabalFlags = {
    build-tool-depends = true;
    ci-build = false;
  }
  // flags;
in
mkDerivation {
  pname = "hpc-bin";
  version = "0.69";
  configureFlags = [
    (if cabalFlags.build-tool-depends then "-fbuild-tool-depends" else "-f-build-tool-depends")
    (if cabalFlags.ci-build then "-fci-build" else "-f-ci-build")
  ];
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    array
    base
    containers
    deepseq
    directory
    filepath
    hpc
    text
  ];
  executableToolDepends = [ ] ++ lib.optionals cabalFlags.build-tool-depends [ happy ];
  testHaskellDepends = [
    base
    directory
    filepath
    process
    tasty
    tasty-golden
    tasty-hunit
    text
    utf8-string
  ];
  description = "Hpc is a tool for generating coverage reports for Haskell projects";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
  mainProgram = "hpc";
}
