# generated-package.nix is auto-generated by regenerate-ghc-ng-packages.sh -- DO NOT EDIT MANUALLY!

{
  mkDerivation,
  array,
  base,
  binary,
  bytestring,
  containers,
  deepseq,
  filepath,
  ghc-boot,
  ghc-boot-th,
  ghc-boot-th-next,
  ghc-heap,
  ghc-internal,
  ghc-prim,
  lib,
  rts,
  transformers,
  unix,
  flags ? { },
}:
let
  cabalFlags = {
    bootstrap = false;
    internal-interpreter = false;
  }
  // flags;
in
mkDerivation {
  pname = "ghci";
  version = "9.15";
  configureFlags = [
    (if cabalFlags.bootstrap then "-fbootstrap" else "-f-bootstrap")
    (if cabalFlags.internal-interpreter then "-finternal-interpreter" else "-f-internal-interpreter")
  ];
  libraryHaskellDepends = [
    array
    base
    binary
    bytestring
    containers
    deepseq
    filepath
    ghc-boot
    ghc-heap
    ghc-internal
    ghc-prim
    rts
    transformers
    unix
  ]
  ++ lib.optionals cabalFlags.bootstrap [ ghc-boot-th-next ]
  ++ lib.optionals (!cabalFlags.bootstrap) [ ghc-boot-th ];
  description = "The library supporting GHC's interactive interpreter";
  license = lib.licenses.bsd3;
}
